"""
Publish Agent - Triggered when user approves a news post.

This agent:
1. Reads the pending post from the GitHub Issue
2. Updates blogPosts.json with the new post
3. Closes the Issue with a success message
"""

import os
import json
import re
import datetime
import requests

# Configuration
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPOSITORY", "ssinghai6/personal_website_portfolio")
ISSUE_NUMBER = os.getenv("ISSUE_NUMBER")
BLOG_DATA_PATH = "src/data/blogPosts.json"


def get_issue_content() -> dict:
    """Fetch the Issue content from GitHub API."""
    if not GITHUB_TOKEN or not ISSUE_NUMBER:
        raise ValueError("GITHUB_TOKEN and ISSUE_NUMBER are required")
    
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{ISSUE_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    response = requests.get(url, headers=headers, timeout=10)
    if response.status_code != 200:
        raise Exception(f"Failed to fetch issue: {response.status_code}")
    
    return response.json()


def extract_post_data(issue_body: str) -> dict:
    """Extract the JSON post data from the Issue body."""
    # Look for the JSON block in the issue body
    json_match = re.search(r"```json\s*(\{.*?\})\s*```", issue_body, re.DOTALL)
    
    if json_match:
        return json.loads(json_match.group(1))
    
    # Fallback: Try to extract manually
    title_match = re.search(r"\*\*Title:\*\*\s*(.+)", issue_body)
    summary_match = re.search(r"\*\*Summary:\*\*\s*(.+)", issue_body)
    tags_match = re.search(r"\*\*Tags:\*\*\s*(.+)", issue_body)
    link_match = re.search(r"\*\*Source:\*\*\s*(.+)", issue_body)
    
    return {
        "title": title_match.group(1).strip() if title_match else "Weekly AI Update",
        "summary": summary_match.group(1).strip() if summary_match else "",
        "tags": [t.strip() for t in tags_match.group(1).split(",")] if tags_match else ["AI"],
        "link": link_match.group(1).strip() if link_match else "#"
    }


def update_blog_data(post_data: dict) -> None:
    """Add the new post to blogPosts.json."""
    try:
        with open(BLOG_DATA_PATH, 'r') as f:
            posts = json.load(f)
    except FileNotFoundError:
        posts = []
    
    # Generate new ID
    new_id = max([p['id'] for p in posts], default=0) + 1
    
    entry = {
        "id": new_id,
        "title": post_data.get("title", f"AI Update {datetime.date.today()}"),
        "date": str(datetime.date.today()),
        "summary": post_data.get("summary", ""),
        "tags": post_data.get("tags", ["AI", "News"]),
        "link": post_data.get("link", "#")
    }
    
    # Prepend the new post (most recent first)
    posts.insert(0, entry)
    
    with open(BLOG_DATA_PATH, 'w') as f:
        json.dump(posts, f, indent=2)
    
    print(f"✅ Added new post: {entry['title']}")
    return entry


def close_issue_with_success(issue_number: str, post_title: str) -> None:
    """Close the Issue and add a success comment."""
    if not GITHUB_TOKEN:
        print("⚠️  No GITHUB_TOKEN, skipping issue close")
        return
    
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    # Add success comment
    comment_url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{issue_number}/comments"
    comment_data = {
        "body": f"""## ✅ Post Published Successfully!

**Title:** {post_title}

The blog post has been added to the website. Changes will be live after the site rebuilds.

---
*This issue will now be closed automatically.*
"""
    }
    requests.post(comment_url, headers=headers, json=comment_data, timeout=10)
    
    # Close the issue
    issue_url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{issue_number}"
    close_data = {"state": "closed"}
    requests.patch(issue_url, headers=headers, json=close_data, timeout=10)
    
    print(f"✅ Issue #{issue_number} closed")


def test_mode():
    """Run in test mode with sample data (no GitHub API needed)."""
    print("=" * 50)
    print("🧪 Running Publish Agent in TEST MODE")
    print("=" * 50)
    
    # Sample post data (similar to what news_agent would generate)
    sample_post = {
        "title": "TEST: AI Weekly Update - Publish Agent Test",
        "summary": "This is a test post to verify the publish agent is working correctly.",
        "content": "## Overview\n\nThis is a test post generated by running `python3 agent/publish_agent.py --test`.\n\n## Key Points\n\n• **Test Verification**: This confirms the publish agent can update blogPosts.json correctly.\n• **Safe to Delete**: You can remove this post from blogPosts.json after testing.",
        "tags": ["Test", "Agent"],
        "sources": [{"title": "Test Source", "url": "https://example.com"}],
        "link": "https://example.com"
    }
    
    print(f"📋 Sample post: {sample_post['title']}")
    print("📝 Updating blogPosts.json...")
    
    entry = update_blog_data(sample_post)
    
    print("\n" + "=" * 50)
    print("✅ TEST PASSED - Post added to blogPosts.json")
    print(f"📄 Post ID: {entry['id']}")
    print("=" * 50)
    print("\n⚠️  Remember to remove the test post from blogPosts.json!")


def main():
    """Publish the approved post."""
    import sys
    
    # Check for test mode
    if "--test" in sys.argv:
        test_mode()
        return
    
    print("=" * 50)
    print("📤 Starting Publish Agent")
    print("=" * 50)
    
    try:
        # 1. Fetch issue content
        print(f"📥 Fetching Issue #{ISSUE_NUMBER}...")
        issue = get_issue_content()
        
        # 2. Extract post data
        print("📋 Extracting post data...")
        post_data = extract_post_data(issue["body"])
        print(f"   Title: {post_data.get('title')}")
        
        # 3. Update blog data
        print("📝 Updating blogPosts.json...")
        entry = update_blog_data(post_data)
        
        # 4. Close the issue
        print("🔒 Closing issue...")
        close_issue_with_success(ISSUE_NUMBER, entry["title"])
        
        print("\n" + "=" * 50)
        print("✅ Publish completed successfully!")
        print("=" * 50)
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        raise


if __name__ == "__main__":
    main()

